[build]
  # This empty command tells Netlify there's no build step,
  # which resolves the "npm run build command is missing" error.
  command = ""
  
  # The directory containing the deploy-ready assets of your site.
  # Since we don't have a frontend build step, this points to the root.
  publish = "/"

  # The directory containing serverless functions.
  functions = "api/"

[build.environment]
  # Lock the Node.js version to a stable LTS version to ensure consistent builds.
  NODE_VERSION = "20"

# Rewrite rule to proxy API calls to Netlify Functions.
[[redirects]]
  # Match all requests starting with /api/
  from = "/api/*"
  # And redirect them to the corresponding Netlify Function.
  # :splat is a placeholder for the wildcard.
  to = "/.netlify/functions/:splat"
  # Status 200 indicates a successful rewrite (not a redirect).
  status = 200
