[build]
  # This command runs the script from package.json to prepare the site.
  command = "npm run build"
  
  # The directory containing the deploy-ready assets of your site.
  # This now points to the 'dist' folder created by the build command.
  publish = "dist"

  # The directory containing serverless functions remains the same.
  functions = "api/"

[build.environment]
  # Lock the Node.js version to a stable LTS version to ensure consistent builds.
  NODE_VERSION = "20"

# Rewrite rule to proxy API calls to Netlify Functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
